CREATE TABLE users(
  id integer PRIMARY KEY GENERATED ALWAYS IDENTITY, 
  first_name VARCHAR(100) NOT NULL, 
  last_name VARCHAR(100) NOT NULL, 
  email VARCHAR(200) NOT NULL UNIQUE, 
  password VARCHAR(255) NOT NULL UNIQUE, 
  created_at TIMESTAMP 
 );


DELETE FROM users;
ALTER TABLE users 
ALTER COLUMN id RESTART WITH 1;